In [1]:
from CartpoleProblem import build_model, getEnv
import numpy as np
import time

Using TensorFlow backend.
/Users/jmargoli/.pyenv/versions/3.5.2/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [2]:
model = build_model()

In [4]:
#Weights not loaded, model will run but do poorly
env = getEnv()

done = False
obs = env.reset()
obs = np.array([obs])
cumReward = 0
while not done:
    print(obs)
    env.render()
    action = np.argmax(model.predict(obs)[0])
    obs[0], reward, done, _ = env.step(action)
    cumReward += reward
    time.sleep(0.01)
print(cumReward)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[[-0.04763789 -0.01581971  0.0234836  -0.01711074]]
[[-0.04795429  0.17895773  0.02314138 -0.30229279]]
[[-0.04437513  0.37374235  0.01709553 -0.58758853]]
[[-0.03690028  0.56862076  0.00534376 -0.8748376 ]]
[[-0.02552787  0.76366966 -0.01215299 -1.16583571]]
[[-0.01025448  0.95894766 -0.03546971 -1.46230397]]
[[ 0.00892448  1.1544859  -0.06471579 -1.76585276]]
[[ 0.0320142   1.35027673 -0.10003284 -2.07793737]]
[[ 0.05901973  1.54626004 -0.14159159 -2.39980336]]
[[ 0.08994493  1.74230703 -0.18958766 -2.73241995]]
10.0


In [3]:
model.load_weights('/Users/jmargoli/Desktop/SatteliteFormations/python/testCode/results/2018:08:17_14:13:52/model.h5')

In [4]:
#Weights loaded, model performs well
env = getEnv()

done = False
obs = env.reset()
obs = np.array([obs])
cumReward = 0
while not done:
    print(obs)
    env.render()
    action = np.argmax(model.predict(obs)[0])
    obs[0], reward, done, _ = env.step(action)
    cumReward += reward
    time.sleep(0.01)
print(cumReward)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[[0.01991395 0.0101156  0.03863507 0.00566291]]
[[ 0.02011626  0.20466278  0.03874833 -0.27458421]]
[[ 0.02420952  0.39921107  0.03325664 -0.55479843]]
[[ 0.03219374  0.59385066  0.02216067 -0.83682073]]
[[ 0.04407075  0.39843316  0.00542426 -0.53725174]]
[[ 0.05203942  0.59347842 -0.00532078 -0.82822062]]
[[ 0.06390899  0.39842962 -0.02188519 -0.53721586]]
[[ 0.07187758  0.59385233 -0.0326295  -0.83671345]]
[[ 0.08375462  0.39919088 -0.04936377 -0.55446807]]
[[ 0.09173844  0.59496995 -0.06045313 -0.862286  ]]
[[ 0.10363784  0.40072093 -0.07769886 -0.58920713]]
[[ 0.11165226  0.20676803 -0.089483   -0.32197601]]
[[ 0.11578762  0.40304273 -0.09592252 -0.64148305]]
[[ 0.12384847  0.20937956 -0.10875218 -0.3804817 ]]
[[ 0.12803607  0.40586421 -0.11636181 -0.70537768]]
[[ 0.13615335  0.21253036 -0.13046937 -0.45147122]]
[[ 0.14040396  0.01947159 -0.13949879 -0.20259357]]
[[ 0.14079339  0.2162

[[-0.55366492 -0.1725551   0.00267608  0.02380217]]
[[-0.55711602 -0.36771533  0.00315213  0.31732823]]
[[-0.56447033 -0.17263841  0.00949869  0.02564103]]
[[-0.56792309 -0.36789529  0.01001151  0.3213057 ]]
[[-0.575281   -0.17291733  0.01643762  0.03179676]]
[[-0.57873935 -0.3682711   0.01707356  0.32962027]]
[[-0.58610477 -0.1733963   0.02366597  0.04237007]]
[[-0.58957269  0.02137843  0.02451337 -0.24275308]]
[[-0.58914513 -0.17408494  0.01965831  0.05756009]]
[[-0.59262682  0.02074971  0.02080951 -0.22885624]]
[[-0.59221183 -0.17466334  0.01623238  0.07031742]]
[[-0.5957051   0.02022218  0.01763873 -0.21720023]]
[[-0.59530065 -0.17514742  0.01329473  0.08099411]]
[[-0.5988036   0.01978145  0.01491461 -0.20746483]]
[[-0.59840797 -0.17555056  0.01076531  0.08988533]]
[[-0.60191898  0.01941544  0.01256302 -0.19938179]]
[[-0.60153068 -0.17588392  0.00857538  0.09723757]]
[[-0.60504835  0.01911408  0.01052013 -0.19272755]]
[[-0.60466607 -0.17615677  0.00666558  0.10325538]]
[[-0.6081892