In [1]:
import numpy as np
import numpy.random as ran
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import sys

%load_ext autoreload
%autoreload 1
%aimport AcrobotPolicy

In [12]:
#Tests for acrobot policy
#Show that action prob handles multi dimensional imputs properly
ran.seed(2)
torch.manual_seed(3)
policy = AcrobotPolicy.acrobot_policy(0.1)
policy.train()

obs = ran.normal(0, 1, (1, 6))
obs = torch.from_numpy(obs).float()
#Confirm these add up to one
print(policy.actionProb(obs, torch.tensor([0], dtype=torch.float)))
print(policy.actionProb(obs, torch.tensor([1], dtype=torch.float)))
print(policy.actionProb(obs, torch.tensor([2], dtype=torch.float)))

#For when we can do more than one action at a time
'''obs = ran.normal(0, 1, (2, 6))
obs = torch.from_numpy(obs).float()
#Confirm these add up to one
print(policy.actionProb(obss, torch.tensor([0, 1], dtype=torch.float)))
print(policy.actionProb(obss, torch.tensor([1, 2], dtype=torch.float)))
print(policy.actionProb(obss, torch.tensor([2, 0], dtype=torch.float)))'''

tensor([0.2890], grad_fn=<TakeBackward>)
tensor([0.3439], grad_fn=<TakeBackward>)
tensor([0.3671], grad_fn=<TakeBackward>)


AssertionError: 